-- Login-by-code feature: table stores ephemeral codes generated by the
-- WpLoginCode CSS plugin when a player types !skins in the CS2 server chat.
-- Codes are 6-character alphanumeric, expire after 5 minutes, and are single-use.

CREATE TABLE IF NOT EXISTS wp_login_codes (
  code VARCHAR(16) NOT NULL PRIMARY KEY,
  steamid VARCHAR(32) NOT NULL,
  expires_at INT UNSIGNED NOT NULL,
  used TINYINT(1) NOT NULL DEFAULT 0,
  INDEX idx_steamid (steamid),
  INDEX idx_expires (expires_at)
);
